# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 430bdaae427819b19b45f2abee0a09e44840574609560e6dbabb2ac8baff8f8b82ace906644b29abd61c2e47b0d15047c8974670a1f9d9edbedadfc029d05609

test:
  secret_key_base: d13be608dbf3a71b5005ad3c5d0c0d9c96ce1469aef964cbdee6d87f8f73d7bd685b101f6dec1833e4fa13c6844c80867982fb884121bf290a93609bcdf2f83a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
